config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  resources :users do
    resources :foods
    resources :exercises
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base

  validates :name, presence: true
  validates :calories, presence: true

  belongs_to :user

  def self.search(search)
    search_Int = search.to_i
    if search == 'all'
      all
    elsif search.present? && (search_Int != 0)
      where('calories = ?', "#{search_Int}")
    elsif search.present? && (search_Int = 0)
      where('name ILIKE ?', "#{search}")
    else
      where(true)
    end
  end

end

app/models/food.rb
class Food < ActiveRecord::Base

  validates :name, presence: true
  validates :calories, presence: true

  belongs_to :user

  def self.search(search)
    search_Int = search.to_i
    if search == 'all'
      all
    elsif search.present? && (search_Int != 0)
      where('calories = ?', "#{search_Int}")
    elsif search.present? && (search_Int = 0)
      where('name ILIKE ?', "#{search}")
    else
      where(true)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :foods
  has_many :exercises
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Food.all
    
  end

  def new
    @user = User.find(params[:user_id])
    @exercise = Exercise.new
  end

  def create
    @user = User.find(params[:user_id])
    @exercise = @user.exercises.new(exercise_params)
    if @exercise.save
      respond_to do |format|
        format.html { redirect_to foods_path }
        format.js
      end
    else
      render :new
    end
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :calories, :user_id)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    if current_user
      if params[:search] && params[:search] != ""
        @foods = current_user.foods.order(params[:foods]).paginate( page: params[:foods_page], :per_page => 5)
        @exercises = current_user.exercises.order(params[:exercises]).paginate( page: params[:exercises_page], :per_page => 5)
        @searchedFoods = current_user.foods.order(params[:searched_foods]).search(params[:search]).paginate( page: params[:searched_foods_page], :per_page => 5)
        @searchedExercises = current_user.exercises.order(params[:searched_exercises]).search(params[:search]).paginate( page: params[:searched_exercises_page], :per_page => 5)
      else
        @searchedFoods = current_user.foods.order(params[:searched_foods] ||= "name").paginate( page: params[:searched_foods_page], :per_page => 5)
        @searchedExercises = current_user.exercises.order(params[:searched_exercises] ||= "name").paginate( page: params[:searched_exercises_page], :per_page => 5)
        @foods = current_user.foods.order(params[:foods] ||= "name").paginate( page: params[:foods_page], :per_page => 5)
        @exercises = current_user.exercises.order(params[:exercises] ||= "name").paginate( page: params[:exercises_page], :per_page => 5)
        # binding.pry
      end
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @user = User.find(params[:user_id])
    @food = Food.new
  end

  def create
    @user = User.find(params[:user_id])
    @food = @user.foods.new(food_params)
    if @food.save
      respond_to do |format|
        format.html { redirect_to foods_path }
        format.js
      end
    else
      render :new
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :calories, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  module ApplicationHelper
    def sortable(object)
      title ||= column.titleize
      direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
      link_to title, :sort => column, :direction => direction
    end
  end

end

app/views/exercises/_exercise.html.erb
<li><%= exercise.name %> for <%= exercise.calories %></li>

app/views/exercises/_form.html.erb
<%= form_for [@user, @exercise], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit "Submit" %>
<% end %>

app/views/exercises/create.js.erb
$("#exercise_list").append('<%= j render @exercise %>');
$("#searched_exercise_list").append('<%= j render @exercise %>');
$("#new_exercise").remove();
$('#new_exercise_link').show();
$('#burned_total').text(<%= current_user.exercises.sum(:calories) %>)
$('#calorie_total').text(<%= current_user.foods.sum(:calories) - current_user.exercises.sum(:calories) %>)

app/views/exercises/new.html.erb
<%= form_for [@user, @exercise] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit "Submit" %>
<% end %>

app/views/exercises/new.js.erb
$('#new_exercise_link').hide().after('<%= j render("form") %>');

app/views/foods/_food.html.erb
<li><%= food.name %> for <%= food.calories %></li>

app/views/foods/_form.html.erb
<%= form_for [@user, @food], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit "Submit" %>
<% end %>

app/views/foods/create.js.erb
$("#food_list").append('<%= j render @food %>');
$("#searched_food_list").append('<%= j render @food %>');
$("#new_food").remove();
$('#new_food_link').show();
$('#consumed_total').text(<%= current_user.foods.sum(:calories) %>)
$('#calorie_total').text(<%= current_user.foods.sum(:calories) - current_user.exercises.sum(:calories) %>)

app/views/foods/index.html.erb
<div class="container">
    <div class="search head col-md-6">
      <%= form_tag user_foods_path(current_user), :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>

    <div class="login head col-md-6">
      <%= link_to "HOME", root_path %>
      <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>

  <div class="col-md-6 col-md-offset-3">
    <div class="block" id="consumed">

      <% if @foods.any? %>
        <div class="total-food">
          <h4>All Consumed Food:</h4>
          <h5>You ate a friggin <span id="consumed_total"><%= @foods.sum(:calories) %></span> calories!!!</h5>
          <ul id="food_list">
            <%= link_to "Name", :foods => "name" %>   <%= link_to "Calories", :foods => "calories" %>

            <% @foods.each do |food| %>
              <%= render food %>
            <% end %>
          </ul>
          <%= will_paginate @foods, :param_name => "foods_page"%>
        </div>
        <div class="searched-food">
          <h4>Searched Food:</h4>
          <ul id="searched_food_list">
            <%= link_to "Name", :searched_foods => "name" %>   <%= link_to "Calories", :searched_foods => "calories" %>

            <% @searchedFoods.each do |food| %>
              <%= render food %>
            <% end %>
          </ul>
          <%= will_paginate @searchedFoods, :param_name => "searched_foods_page" %>
        </div>
      <% else %>
        <p>You really should eat someting</p>
      <% end %>
      <%= link_to 'Enter Food', new_user_food_path(current_user), id: "new_food_link", remote: true %>
    </div>

    <div class="block" id="burned">

      <% if @exercises.any? %>
      <div class="total-exercise">
        <h4>All Done Exercise:</h4>
        <h5>You burned a friggin <span id="burned_total"><%= @exercises.sum(:calories) %></span> calories!!!</h5>
        <ul id="exercise_list">
          <%= link_to "Name", :exercises => "name" %>   <%= link_to "Calories", :exercises => "calories" %>

          <% @exercises.each do |exercise| %>
            <%= render exercise %>
          <% end %>
        </ul>
        <%= will_paginate @exercises, :param_name => "exercises_page" %>
      </div>
      <div class="searched-exercise">
        <h4>Searched Exercise:</h4>
        <ul id="searched_exercise_list">
          <%= link_to "Name", :searched_exercises => "name" %>   <%= link_to "Calories", :searched_exercises => "calories" %>

          <% @searchedExercises.each do |exercise| %>
            <%= render exercise %>
          <% end %>
        </ul>
        <%= will_paginate @searchedExercises, :param_name => "searched_exercises_page" %>
      </div>
      <% else %>
        <p>You really should do someting</p>
      <% end %>
      <%= link_to 'Enter Exercise', new_user_exercise_path(current_user), id: "new_exercise_link", remote: true%>
    </div>

    <div class="block" id="total">
      <h4>Well that is a total of <span id="calorie_total"><%= @foods.sum(:calories) - @exercises.sum(:calories) %></span> straight
      <% if ( (@foods.sum(:calories) - @exercises.sum(:calories)) > 0) %>
        to your hips.
      <% else %>
        from your hips.
      <% end %>
      </h4>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<%= form_for [@user, @food] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit "Submit" %>
<% end %>

app/views/foods/new.js.erb
$('#new_food_link').hide().after('<%= j render("form") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>